name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Sanity check - Load model
      run: |
        python -c "import pickle; open('titanic_model.pkl', 'rb')"

    - name: Run FastAPI application
      run: |
        uvicorn app:app --host 0.0.0.0 --port 8000 --log-level info &
        sleep 5
        curl -X POST "http://127.0.0.1:8000/predict" -H "Content-Type: application/json" -d '{"Sex": 1, "Age": 22}'